// const data = {
//     "questions": [
//         {
//             "questionNumber": "Вопрос №1",
//             "question": "Что такое условный оператор?",
//             "var1": "Конструкция, что выполняет код несколько раз",
//             "var2": "Конструкция для создания определенной переменной",
//             "var3": "Оператор сравнения значений",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/1",
//             "type": "js"

//         },
//         {
//             "questionNumber": "Вопрос №2",
//             "question": "Какие циклы есть в языке JavaScript?",
//             "var1": "for, forMap, foreach, while",
//             "var2": "for, while, do while, foreach",
//             "var3": "for, while, do while",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/2",
//             "type": "js"
//         },
//         {
//             "questionNumber": "Вопрос №3",
//             "question": "Какие функции выполняет JS?",
//             "var1": "Отвечает за функции на стороне клиента",
//             "var2": "Отвечает за работу с базами данных",
//             "var3": "Выполняет работу с сервером",
//             "value1" : "true",
//             "value2" : "false",
//             "value3" : "false",
//             "path": "/3",
//             "type": "js"
//         },
//         {
//             "questionNumber": "Вопрос №4",
//             "question": "Где верно указан вывод данных?",
//             "var1": "prompt('Hello')",
//             "var2": "console.log('Hello');",
//             "var3": "documentWrite('Hello');",
//             "value1" : "false",
//             "value2" : "true",
//             "value3" : "false",
//             "path": "/4",
//             "type": "js"
//         },
//         {
//             "questionNumber": "Вопрос №5",
//             "question": "Где верно указан запуск всплывающего окна?",
//             "var1": "info ('Hi')",
//             "var2": "alert ('Hi')",
//             "var3": "new alert ('Hi')",
//             "value1" : "false",
//             "value2" : "true",
//             "value3" : "false",
//             "path": "/5",
//             "type": "js"
//         },
//         {
//             "questionNumber": "Вопрос №6",
//             "question": "В чем отличие между локальной и глобальной переменной?",
//             "var1": "Глобальные видны повсюду, локальные только в функциях",
//             "var2": "Локальные можно переопределять, глобальные нельзя",
//             "var3": "Глобальные можно переопределять, локальные нельзя",
//             "value1" : "true",
//             "value2" : "false",
//             "value3" : "false",
//             "path": "/6",
//             "type": "js"
//         },
//         {
//             "questionNumber": "Вопрос №7",
//             "question": "В чем разница между confirm и prompt?",
//             "var1": "Они ничем не отличаются",
//             "var2": "confirm вызывает диалоговое окно с полем для ввода, prompt - окно с подтверждением",
//             "var3": "prompt вызывает диалоговое окно с полем для ввода, confirm - окно с подтверждением",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/7",
//             "type": "js"
//         },
//         {
//             "questionNumber": "Вопрос №8",
//             "question": "Какая переменная записана неверно?",
//             "var1": "var num = 'STRING';",
//             "var2": "var number = 12,5;",
//             "var3": "var isDone = 0;",
//             "value1" : "false",
//             "value2" : "true",
//             "value3" : "false",
//             "path": "/8",
//             "type": "js"
//         },
//         {
//             "questionNumber": "Вопрос №9",
//             "question": "Где можно использовать JavaScript?",
//             "var1": "Серверные приложения",
//             "var2": "Веб-приложения",
//             "var3": "Можно во всех перечисленных",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/9",
//             "type": "js"
//         },
//         {
//             "questionNumber": "Вопрос №10",
//             "question": "Что выводит Array.length?",
//             "var1": "Возвращает число (индексы) этого массива",
//             "var2": "Устанавливает или возвращает число элементов этого массива",
//             "var3": "Указывает сколько типов внутри элементов этого массива",
//             "value1" : "false",
//             "value2" : "true",
//             "value3" : "false",
//             "path": "/10",
//             "type": "js"
//         },
//         {
//             "questionNumber": "Вопрос №1",
//             "question": "Что такое Git?",
//             "var1": "Это облачное хранилище",
//             "var2": "Это сервер для ваших проектов",
//             "var3": "Это распределённая система управления версиями",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/1",
//             "type": "git"
//         },
//         {
//             "questionNumber": "Вопрос №2",
//             "question": "Можно ли отследить хронологию событий через Git?",
//             "var1": "Да, можно отследить дату, автора и изменения что были внесены",
//             "var2": "Да, но лишь отслеживать добавленные файлы",
//             "var3": "Да, но лишь даты кто и что добавил в проект",
//             "value1" : "true",
//             "value2" : "false",
//             "value3" : "false",
//             "path": "/2",
//             "type": "git"
//         },
//         {
//             "questionNumber": "Вопрос №3",
//             "question": "Как в Git установить глобально Email пользователя?",
//             "var1": "git user.email",
//             "var2": "git --global user.email",
//             "var3": "git config --global user.email",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/3",
//             "type": "git"
//         },
//         {
//             "questionNumber": "Вопрос №4",
//             "question": "В каком редакторе можно работать с Git?",
//             "var1": "Только в редакторе Atom",
//             "var2": "Можно во всех редакторах, что поддерживают подключение терминала",
//             "var3": "Можно во всех редакторах",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/4",
//             "type": "git"
//         },
//         {
//             "questionNumber": "Вопрос №5",
//             "question": "Как можно установить Git?",
//             "var1": "Лишь через официальный сайт",
//             "var2": "Лишь через терминал (командную строку)",
//             "var3": "Можно через сайт или командную строку",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/5",
//             "type": "git"
//         },
//         {
//             "questionNumber": "Вопрос №6",
//             "question": "Какая команда в терминале служит для перехода к нужной папке?",
//             "var1": "cd 'папка'",
//             "var2": "to 'папка'",
//             "var3": "open 'папка'",
//             "value1" : "true",
//             "value2" : "false",
//             "value3" : "false",
//             "path": "/6",
//             "type": "git"
//         },
//         {
//             "questionNumber": "Вопрос №7",
//             "question": "Сколько людей могут работать через Git над одним проектом?",
//             "var1": "Не более 30",
//             "var2": "Неограниченное количество",
//             "var3": "Не более 50",
//             "value1" : "false",
//             "value2" : "true",
//             "value3" : "false",
//             "path": "/7",
//             "type": "git"
//         },
//         {
//             "questionNumber": "Вопрос №8",
//             "question": "Как в Git не получится установить значение «Имя пользователя»?",
//             "var1": "git config --global user.name",
//             "var2": "git user.name",
//             "var3": "git config user.name",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/8",
//             "type": "git"
//         },
//         {
//             "questionNumber": "Вопрос №9",
//             "question": "Git и GitHub одно и тоже самое?",
//             "var1": "Да. Git это сокращение от GitHub",
//             "var2": "Нет, это продукты разных компаний",
//             "var3": "Оба продукта разработаны одной компанией, но они не одно и тоже",
//             "value1" : "false",
//             "value2" : "false",
//             "value3" : "true",
//             "path": "/9",
//             "type": "git"
//         },
//         {
//             "questionNumber": "Вопрос №10",
//             "question": "Что такое GitHub?",
//             "var1": "Графический интерфейс для работы с Git",
//             "var2": "Веб-сервис для хостинга IT-проектов",
//             "var3": "Технология для контроля версий проектове",
//             "value1" : "false",
//             "value2" : "true",
//             "value3" : "false",
//             "path": "/10",
//             "type": "git"
//         }
//     ]
// }

